# Generated by Django 5.2.8 on 2025-12-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articelsite', '0002_alter_articel_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='articel',
            name='author',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
