# Generated by Django 5.2.8 on 2025-12-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articelsite', '0003_articel_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='articel',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
