# Generated by Django 5.2.8 on 2025-12-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articelsite', '0004_articel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='articel',
            name='background_img',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
