# Generated by Django 5.2.8 on 2025-12-03 10:43

import articelsite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articelsite', '0005_articel_background_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articel',
            name='background_img',
            field=models.ImageField(upload_to=articelsite.models.background_image_path),
        ),
    ]
