# Generated by Django 5.2.8 on 2025-12-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articelsite', '0006_alter_articel_background_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articel',
            name='author',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='articel',
            name='pub_date',
            field=models.DateTimeField(blank=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='articel',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
