# Generated by Django 5.2.8 on 2025-12-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articelsite', '0007_alter_articel_author_alter_articel_pub_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articel',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
