# Generated by Django 5.2.8 on 2025-12-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articelsite', '0008_alter_articel_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='articel',
            name='theme',
            field=models.CharField(choices=[('israel', 'Israel'), ('bible', 'Bible'), ('testimonies', 'Testimonies')], default='israel', max_length=20),
        ),
    ]
