# Generated by Django 5.2.8 on 2025-12-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articelsite', '0009_articel_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articel',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='articel',
            name='text',
            field=models.TextField(max_length=100000),
        ),
    ]
